# What storage type to use. Currently only supports flatfile.
StorageType: flatfile

# Settings related to flatfile storage type.
FlatFile:
  # If the plugin should attempt to save the storage.yml async.
  AttemptAsyncSave: false

# Needed for all Inventory/GUI Placeholders, in inventory title, item names and item lores.
# Changing this requires a restart.
UsePlaceholderAPI: true

# This will override all the users its importing from.
Import:
  # Name of the file to import from. If the file does not exist, it will create it.
  # Set to empty string to disable import command.
  File: 'oldusers.yml'

  # Path to where UUIDs are stored.
  UuidSection: 'Storage'

  # UUID Will be added to the start of the message.
  CreditsPath: '.Credits'

# Time in ms for how long to wait between clicking items in the GUI can do something.
# As in, if you click an item, you've gotta wait this amount of time, before clicking another item/same item can do something.
InventoryClickDelay: 1000

McmmoInventory:
  # All placeholders require PlaceholderAPI.
  # Title of the inventory.
  Title: '&c%player_name%''s Credits: %credits_credits%'
  # How many rows the inventory should have.
  Rows: 3
  Items:
    # Does not matter what this is, as long as its unique.
    Acrobatics:
      # Material of the item. Valid materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
      Material: DIAMOND_BOOTS

      # Name of the item.
      Name: '&bAcrobatics'

      # Lore of the item.
      Lore:
        - '&7Click to add levels to your &bAcrobatics &7skill.'
        - '&7Your current &bAcrobatics &7level: %mcmmo_level_acrobatics%'

      # What happens when you click the item in the inventory. currently only mmolvl works. put empty string for nothing to happen.
      ItemAction: 'mmolvl::ACROBATICS'

      # Valid item flags: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
      ItemFlags:
        - 'HIDE_ATTRIBUTES'

      # If the inventory should close after clicking the item
      CloseInventory: true

      # Item damage.
      #Damage: 0

      # If the item should glow like it is enchanted, without showing any enchants.
      #FakeEnchant: false

      # Position of the item in the Inventory.
      Position-X: 2
      Position-Y: 1
    Alchemy:
      Material: POTION
      Name: '&bAlchemy'
      Lore:
        - '&7Click to add levels to your &bAlchemy &7skill.'
        - '&7Your current &bAlchemy &7level: %mcmmo_level_alchemy%'
      ItemAction: 'mmolvl::ALCHEMY'
      CloseInventory: true
      Position-X: 4
      Position-Y: 1
    Archery:
      Material: BOW
      Name: '&bArchery'
      Lore:
        - '&7Click to add levels to your &bArchery &7skill.'
        - '&7Your current &bArchery &7level: %mcmmo_level_archery%'
      ItemAction: 'mmolvl::ARCHERY'
      CloseInventory: true
      Position-X: 6
      Position-Y: 1
    Axes:
      Material: DIAMOND_AXE
      Name: '&bAxes'
      Lore:
        - '&7Click to add levels to your &bAxes &7skill.'
        - '&7Your current &bAxes &7level: %mcmmo_level_axes%'
      ItemAction: 'mmolvl::AXES'
      ItemFlags:
        - 'HIDE_ATTRIBUTES'
      CloseInventory: true
      Position-X: 8
      Position-Y: 1
    Excavation:
      Material: DIAMOND_SPADE
      Name: '&bExcavation'
      Lore:
        - '&7Click to add levels to your &bExcavation &7skill.'
        - '&7Your current &bExcavation &7level: %mcmmo_level_excavation%'
      ItemAction: 'mmolvl::EXCAVATION'
      ItemFlags:
        - 'HIDE_ATTRIBUTES'
      CloseInventory: true
      Position-X: 1
      Position-Y: 2
    Fishing:
      Material: FISHING_ROD
      Name: '&bFishing'
      Lore:
        - '&7Click to add levels to your &bFishing &7skill.'
        - '&7Your current &bFishing &7level: %mcmmo_level_fishing%'
      ItemAction: 'mmolvl::FISHING'
      CloseInventory: true
      Position-X: 3
      Position-Y: 2
    Herbalism:
      Material: SUGAR_CANE
      Name: '&bHerbalism'
      Lore:
        - '&7Click to add levels to your &bHerbalism &7skill.'
        - '&7Your current &bHerbalism &7level: %mcmmo_level_herbalism%'
      ItemAction: 'mmolvl::HERBALISM'
      CloseInventory: true
      Position-X: 5
      Position-Y: 2
    Mining:
      Material: DIAMOND_PICKAXE
      Name: '&bMining'
      Lore:
        - '&7Click to add levels to your &bMining &7skill.'
        - '&7Your current &bMining &7level: %mcmmo_level_mining%'
      ItemAction: 'mmolvl::MINING'
      ItemFlags:
        - 'HIDE_ATTRIBUTES'
      CloseInventory: true
      Position-X: 7
      Position-Y: 2
    Repair:
      Material: IRON_BLOCK
      Name: '&bRepair'
      Lore:
        - '&7Click to add levels to your &bRepair &7skill.'
        - '&7Your current &bRepair &7level: %mcmmo_level_repair%'
      ItemAction: 'mmolvl::REPAIR'
      CloseInventory: true
      Position-X: 9
      Position-Y: 2
    Swords:
      Material: DIAMOND_SWORD
      Name: '&bSwords'
      Lore:
        - '&7Click to add levels to your &bSwords &7skill.'
        - '&7Your current &bSwords &7level: %mcmmo_level_swords%'
      ItemAction: 'mmolvl::SWORDS'
      ItemFlags:
        - 'HIDE_ATTRIBUTES'
      CloseInventory: true
      Position-X: 2
      Position-Y: 3
    Taming:
      Material: BONE
      Name: '&bTaming'
      Lore:
        - '&7Click to add levels to your &bTaming &7skill.'
        - '&7Your current &bTaming &7level: %mcmmo_level_taming%'
      ItemAction: 'mmolvl::TAMING'
      CloseInventory: true
      Position-X: 4
      Position-Y: 3
    Unarmed:
      Material: GLASS
      Name: '&bUnarmed'
      Lore:
        - '&7Click to add levels to your &bUnarmed &7skill.'
        - '&7Your current &bUnarmed &7level: %mcmmo_level_unarmed%'
      ItemAction: 'mmolvl::UNARMED'
      CloseInventory: true
      Position-X: 6
      Position-Y: 3
    Woodcutting:
      Material: IRON_AXE
      Name: '&bWoodcutting'
      Lore:
        - '&7Click to add levels to your &bWoodcutting &7skill.'
        - '&7Your current &bWoodcutting &7level: %mcmmo_level_woodcutting%'
        - '&7Level cap: &c%credits_mcmmocap_woodcutting%'
      ItemAction: 'mmolvl::WOODCUTTING'
      ItemFlags:
        - 'HIDE_ATTRIBUTES'
      CloseInventory: true
      Position-X: 8
      Position-Y: 3

# All the messages. Explains itself. Does not support PlaceholderAPI, only the placeholders provided in each message.
Messages:
  NoLevelCap: '&cNone'
  NoPermission: '&4You do not have permission to do that.'
  CreditsCmd:
    Amount: '&cAmount cannot be 0 or less.'
    PlayerNotOnline: '&cUnable to find player ''%player%''. Are they online?'
    Add:
      Usage: '&cIncorrect command usage. Try: /credits add <player> <amount>'
      Added: '&aSuccessfully added %amount% credits to %player%.'
      Error: '&cSomething went wrong trying to add credits to %player%! check console for potential errors.'
      Target: '&aYou have received %amount% credits.'
    Take:
      Usage: '&cIncorrect command usage. Try: /credits take <player> <amount>'
      Removed: '&aSuccessfully removed %amount% credits from %player%.'
      Error: '&cSomething went wrong trying to take credits from %player%! Do they have enough?'
      Target: '&c%amount% of your credits vanished.'
    Send:
      Sent: '&aYou''ve sent %amount% credits to %player%'
      Received: '&a%player% has sent you %amount% credits'
      NotEnough: '&aYou do not have enough credits to do that.'
      Usage: '&cIncorrect command usage. Try: /credits send <player> <amount>'
      Error: '&cSomething went wrong trying to send credits. Try again or contact staff.'
      NotSelf: '&cYou cannot send credits to yourself.'
    View:
      Self: '&7You currently have &a%amount% &7Credits.'
      Other: '&a%player% &7current has &a%amount% &7Credits.'
      OtherUsage: '&cIncorrect command usage. Try: /credits <player>'
    Import:
      Attempted: '&aAttempted to import from configured file. Check console for potential errors.'
    Reload: '&aAttempted to reload configuration.'
    Help:
    - '&7===== &aCredits Help &7====='
    - '&a/Redeem &7- Open McMMO Redeem GUI'
    - '&a/Credits &7- See how many credits you have'
    - '&a/Credits [player] &7- See how many credits [player] has'
    - '&a/Credits send <player> <amount>'
    - '&a/Credits add <player> <amount>'
    - '&a/Credits take <player> <amount>'
    - '&a/Credits reload'
  MissingCredits: '&cYou do not have enough credits for that.'
  McMMO:
    EnterAmount: '&aPlease type how many credits you wish to redeem. 0 to cancel.'
    OverLimit: '&cYou cannot set your level to %target% when the cap is %cap%!'
    Cancel: '&cYou are no longer redeeming McMMO credits.'
    Redeemed: '&7You''ve added &a%amount% &7level(s) to &a%skill%'
    Error: '&cSomething went wrong. Are you sure that you have enough credits?'